### ISSUE TITLE
Two devices reported as single device when reported in uhd_find_devices

### ISSUE THREAD

**Issue by ncorgan** [pothosware/SoapyAudio#15]
SoapySDRUtil correctly reports two separate audio devices as two devices, as does the PothosFlow host explorer.

```
ncorgan@edi:~/dev/sdr/build/SoapyAudio$ SoapySDRUtil --find=driver=audio
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################


RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

Found device 0
  default_input = True
  default_output = False
  device_id = 0
  driver = audio
  label = hw:HDA Intel PCH,0

Found device 1
  default_input = False
  default_output = False
  device_id = 2
  driver = audio
  label = default
```

However, uhd_find_devices outputs:

```
ncorgan@edi:~/dev/sdr/build/SoapyAudio$ uhd_find_devices 
[INFO] [UHD] linux; GNU C++ version 7.4.0; Boost_106501; UHD_3.14.1.HEAD-0-gbfb9c1c7

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: 
    default_input: False
    default_input: True
    default_output: False
    device_id: 0
    device_id: 2
    driver: audio
    label: default
    label: hw:HDA Intel PCH,0
    type: soapy
```

uhd_usrp_probe just crashes, but that may be a separate issue.

**Comment by guruofquality** [comment]
Thats extremely special. I have not replicated it, but I have an idea: https://github.com/pothosware/SoapyUHD/blob/master/UHDSoapyDevice.cpp#L915 

So the erase is supposed to be working on a copy of the dictionary, but if its not, this could mess up the iterator and cause buggy behaviour. So it may be boost specific.

```
    BOOST_FOREACH(SoapySDR::Kwargs found, SoapySDR::Device::enumerate(args))
    {
        found.erase(SOAPY_UHD_NO_DEEPER);
        result.push_back(kwargsToDict(found));
        result.back()["type"] = "soapy";
    }
```

Does changing that to a normal c++11 for help, or adding prints show anything insightful?

**Comment by ncorgan** [comment]
I switched to:

```
const auto foundDevices = SoapySDR::Device::enumerate(args);
    for(auto found: foundDevices)
```

The same thing happened. Device::enumerate does return two devices, so the issue isn't there. I'll keep digging.

**Comment by ncorgan** [comment]
I confirmed that the uhd::device_addrs_t being returned is of the correct size, even with the old code. It looks like something weird is going on with UHD itself. uhd_find_devices got weirdly complicated.

**Comment by ncorgan** [comment]
Yup, that's it. uhd_find_devices (3.14.1.1) doesn't like when a device doesn't have a serial. I tweaked SoapyAudio to set the serial to the label, and it worked fine.

**Comment by guruofquality** [comment]
Since the serial is now critical (and I think SoapyAudio should have one if possible) the fix should be to make UHDSoapyDevice fill in a serial if missing to debugify things within libuhd. Sounds right to you?

**Comment by ncorgan** [comment]
That sounds right. Unless I'm mistaken, Driver+Label should be unique enough, or we could just hash the other KWarg entries for uniqueness, since the end value has no real meaning anyway.

Scoped to SoapyAudio, RtAudio doesn't expose a specific serial for devices (it probably wouldn't apply universally anyway), so I'd say UHDSoapyDevice should do the work for this case.

**Comment by ncorgan** [comment]
Confirmed:

```
ncorgan@edi:~/dev/sdr/build/SoapyUHD$ uhd_find_devices 
[INFO] [UHD] linux; GNU C++ version 7.4.0; Boost_106501; UHD_3.14.1.HEAD-0-gbfb9c1c7
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: 16033392107956607430
    default_input: True
    default_output: True
    device_id: 0
    driver: audio
    label: hw:HDA Intel PCH,0
    type: soapy


--------------------------------------------------
-- UHD Device 1
--------------------------------------------------
Device Address:
    serial: 5743241338020009551
    default_input: False
    default_output: False
    device_id: 2
    driver: audio
    label: default
    type: soapy
```
