### ISSUE TITLE
Add to Pothos SDR build

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyAudio#7]
- dont forget rtaudio

**Comment by guruofquality** [comment]
@cjcliffe what have you been using for rtaudio on windows: Is there a pre-built package, or are you adding it to a build script from source, etc..?
- https://github.com/thestk/rtaudio

**Comment by cjcliffe** [comment]
There's no lib for RtAudio, already included -- it's just a header and a big .cpp file :)

**Comment by guruofquality** [comment]
Ahh, I didnt notice that. That makes life easier.

To complicate things, maybe we make an attempt to use a system installed rtaudio when available. But I will leave that for another day. :-P

**Comment by guruofquality** [comment]
https://github.com/pothosware/PothosSDR/commit/7040881fda505d696e9e4ffb807288dd56efe9cf
